version: '3'
services:
  api_evaluation_notebook:
    build:
      context: .
      dockerfile: Dockerfile.ApiEvaluationNotebook
    network_mode: "host"
    environment:
      - JUPYTER_PASS=pass
    volumes:
      - ${PWD}/OasisPiWind/tests/inputs:/home/run/data
      - ${PWD}/OasisPiWind/analysis_settings.json:/home/run/data/analysis_settings.json
