name: Evaluation Installation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: run installation
      run: ./install.sh

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install test deps
      run: |
        python -m pip install --upgrade pip
        pip install -r OasisPiWind/tests/requirements.in

    - name: run PiWind test
      run: pytest OasisPiWind/tests/test_piwind_integration.py -v --use-running-containers --docker-compose=oasis-platform.yml -k all_outputs
      env:
        WORKER_API_VER: 'v1'
